### ISSUE TITLE
Love the project!

### ISSUE THREAD

**Issue by Tarhiel** [MarioSilvaGH/Rich-Presence-U#1]
Would you consider adding Fantasy Life for 3ds?

**Comment by MarioSilvaGH** [comment]
If I get an icon for this game I can add it at any time.
If you have one, you can submit through this form: [https://forms.gle/SztU5GdQEgwx45GX8](https://forms.gle/SztU5GdQEgwx45GX8)
or contact me directly on [Discord](https://discord.gg/wZGW8DZ)
